# Nginx Service
nginx:
  build: ./.docker/nginx
  ports:
    - 80:80
    - 443:443
     healthcheck:
      test: curl --fail http://localhost:80/443 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  networks:
    default:
      aliases:
        - frontend.demo.test
  volumes:
    - ./src/backend:/var/www/backend
    - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    - phpmyadmindata:/var/www/phpmyadmin
    #- ./.docker/nginx/certs:/etc/nginx/certs
    - ./.docker/nginx/certs:/usr/local/share/ca-certificates
  depends_on:
    - backend
    - frontend
    - phpmyadmin